export default  {
  products: [
    {
      _id: '1',
      name: "Playstation 5",
      category: "Gaming Consoles",
      image: "/images/ps5v3.jpg",
      price: 900,
      brand: " Sony",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: "Red Dead Redemtion 2",
      category: "Games",
      image: "/images/RDR2.png",
      price: 90,
      brand: " Rockstar",
      rating: 5,
      numReviews: 2,
      countInStock: 6,
    },
    {
      _id: '3',
      name: "GTA 5",
      category: "Games",
      image: "/images/gta5.jpg",
      price: 70,
      brand: " Rockstar",
      rating: 4.0,
      numReviews: 35,
      countInStock: 6,
    },
    {
      _id: '4',
      name: "Skyrim 5",
      category: "Games",
      image: "/images/skyrim.jpg",
      price: 30,
      brand: " Bathseda",
      rating: 4.8,
      numReviews: 77,
      countInStock: 6,
    },
    {
      _id: '5',
      name: "Playstation 5",
      category: "Gaming Consoles",
      image: "/images/ps4.jpg",
      price: 600,
      brand: " Sony",
      rating: 4.2,
      numReviews: 37,
      countInStock: 20,
    },
    {
      _id: '6',
      name: "Cyberpunk 2077",
      category: "Games",
      image: "/images/cyberpunkPC.jpg",
      price: 75,
      brand: " CD Project",
      rating: 3.5,
      numReviews: 57,
      countInStock: 80,
    },
  ]
}

